TS_PATH = './data/timeseries'
CLAS_PATH = 'data/classification'
RES_PATH = './results'
FOLDS_PATH =  RES_PATH + '/folds.csv'
MODELS_METRICS_PATH = RES_PATH + '/models_metrics.csv'
FIT_MODELS_METRICS_PATH = RES_PATH + '/models_metrics_fit.csv'
EVAL_MODELS_METRICS_PATH = RES_PATH + '/models_metrics_eval.csv'
MODELS_PATH = RES_PATH + "/models"
PREDICTION_PATH = RES_PATH + "/predictions"
PREDICTION_TRAIN_PATH = RES_PATH + "/predictions_train"
PREDICTION_VAL_PATH = RES_PATH + "/predictions_val"
PREDICTION_TEST_PATH = RES_PATH + "/predictions_test"
THRESHOLDS_PATH = RES_PATH + "/thresholds.csv"
COMPARISON_PATH = RES_PATH + "/comparison.csv"
COMPARISON_PROJECT_PATH = RES_PATH + "/comparison_project.csv"
CFG_PATH = RES_PATH + "/cfg"
CFG_EVAL_PATH = RES_PATH + "/cfg_eval.csv"
WEE_PATH = RES_PATH + "/wee.csv"
PD_PATH = RES_PATH + "/performance_deviation.csv"
TC_PATH = RES_PATH + "/time_cost.csv"
WEE_COMPARISON_PATH = RES_PATH + "/wee_comparison.csv"
PD_COMPARISON_PATH = RES_PATH + "/performance_deviation_comparison.csv"
TC_COMPARISON_PATH = RES_PATH + "/time_cost_comparison.csv"
WINDOW_SIZE = 100
EPOCHS = 500
ROP_PATIENCE = 20
ES_PATIENCE = 50
BATCH_SIZE = 1024
VALIDATION_SPLIT_SIZE = 0.25
N_FOLDS = 5